### ISSUE TITLE
SyntaxError: Unexpected Token Functions & Types not supported.

### ISSUE THREAD

**Issue by vabtrix** [basiqio/basiq-sdk-nodejs#1]
Trying to include Basiq-sdk-nodejs in my existing typescript project and keep getting the following error.

What is the right way to use the sdk with a Typescript 

```
Could not find a declaration file for module 'basiq-sdk-nodejs'. 'c:/<DIR>/node_modules/basiq-sdk-nodejs/index.js' implicitly has an 'any' type.
  Try `npm install @types/basiq-sdk-nodejs` if it exists or add a new declaration (.d.ts) file containing `declare module 'basiq-sdk-nodejs';`
```

```
C:\<DIR>\node_modules\basiq-sdk-nodejs\index.js:1
SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (<FolderDir>\functions\src\index.js:4:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (<FolderDir>\functions\index.js:112:26)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
```

**Comment by vabtrix** [comment]
I did try to build the SDK , but ended up with the same error. Probably there is an issue when using this sdk with Typescript project.
