### ISSUE TITLE
Facing the following issue while using the BasiQ SDK

### ISSUE THREAD

**Issue by vabtrix** [basiqio/basiq-sdk-nodejs#10]
`TypeError: Cannot read property 'reduce' of undefined
    at new n (/srv/node_modules/basiq-sdk-nodejs/index.js:1:12220)
    at Request._callback (/srv/node_modules/basiq-sdk-nodejs/index.js:1:11914)
    at Request.self.callback (/srv/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/srv/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/srv/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)`

**Comment by aterentic-basiq** [comment]
@vabtrix , this should be fixed by #9, please close issue if it works for you.

**Comment by vabtrix** [comment]
Issue fixed. Thanks @aterentic
