### ISSUE TITLE
Syntax Error on deleting user from userService

### ISSUE THREAD

**Issue by aaronhayes** [basiqio/basiq-sdk-nodejs#4]
I've been following the [example code](https://github.com/basiqio/basiq-sdk-nodejs#delete-a-user) on trying to delete a user; however I keep getting a syntax error (from within this SDK). I should note that the API call to Basiq's server succeeds, so on subsequent attempts I get the expected `Requested resource is not found` message.

My code that is failing:
```JavaScript
const currentUser = userService.for(basiqUserId);
await userService.delete(currentUser);  // <-- This line fails
```

Error Produced:
```
Debug: internal, implementation, error 
    SyntaxError: Uncaught error: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Request._callback (/node_modules/basiq-sdk-nodejs/index.js:1:11882)
    at Request.self.callback (/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

**Comment by aaronhayes** [comment]
Okay this is probably because the delete endpoints return an empty body upon success; and then somewhere `JSON.parse("")` is being called which throws the error.

I'm thinking https://github.com/basiqio/basiq-sdk-nodejs/blob/master/src/helpers/API.js#L43 is the culprit.

**Comment by nenadlukic** [comment]
Thank you for finding and fixing this!
